dist: bionic

language: node_js

node_js:
  - 12
  - 10
  - 8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache  # Cypress binary

script:
  - npm run e2e

jobs:
  include:
    - stage: build
      script:
        - npm run lint
        - npm test
    - stage: deploy
      script:
        - npm run build
      deploy:
        - provider: cloudfoundry
          skip_cleanup: true
          api: https://api.run.pivotal.io
          username: $CF_USERNAME
          password: $CF_PASSWORD
          organization: $CF_ORG
          space: $CF_SPACE
          on:
            branch: master
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: starter-kit-ci

stages:
  - build
  - test
  - deploy
