dist: xenial

language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache  # Cypress binary

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - npm run e2e

deploy:
  - provider: cloudfoundry
    skip_cleanup: true
    api: https://api.run.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: $CF_ORG
    space: $CF_SPACE
    on:
      branch: master
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: starter-kit-ci
