version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:dubnium

docker-e2e: &docker-e2e
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Docker E2E
        command: docker-compose run e2e run e2e:run

orbs:
  cypress: cypress-io/cypress@1.7.0
  # Note that you will have to opt-in to third party orbs...

jobs:
  test:
    <<: *defaults
    environment:
      CYPRESS_INSTALL_BINARY: 0
      JEST_JUNIT_OUTPUT_DIR: './reports/jest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - starter-kit-deps-{{ checksum "package-lock.json" }}
            - starter-kit-deps- # fallback
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: starter-kit-deps-{{ checksum "package-lock.json" }}
          paths:
            - "~/.npm"
      - run:
          name: Lint source code
          command: npm run lint
      - run:
          name: Test source code
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports
  verify-boron:
    environment:
      NODE_RELEASE: boron
    <<: *defaults
    <<: *docker-e2e
  verify-carbon:
    environment:
      NODE_RELEASE: carbon
    <<: *defaults
    <<: *docker-e2e
  verify-dubnium:
    environment:
      NODE_RELEASE: dubnium
    <<: *defaults
    <<: *docker-e2e

workflows:
  build:
    jobs:
      - test
      - cypress/run:
          requires:
            - test
          start: npm run serve
          wait-on: 'http-get://localhost:3000'
  verify:
    jobs:
      - verify-boron
      - verify-carbon
      - verify-dubnium
